require: rubocop-rake

AllCops:
  TargetRubyVersion: 2.6.7

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Metrics/BlockLength:
  Exclude:
    - 'fudo3.gemspec'
    - 'spec/**/*'
