require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.3
  NewCops: enable

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Metrics/BlockLength:
  Exclude:
    - 'fudo3.gemspec'
    - 'spec/**/*'
